version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_link
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - ./wwlink_system.sql:/docker-entrypoint-initdb.d/schema.sql:ro


