version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_healthlife
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: 'wwlink_system'
      MYSQL_ROOT_PASSWORD: '@sd452Wd5@mP'
    ports:
      - 3306:3306
    volumes:
      - ./wwlink_system.sql:/docker-entrypoint-initdb.d/schema.sql:ro 
